//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 GflsScanerTest.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GFLSSCTYPE                  129
#define IDD_DIALOG_IMAGEINFO            130
#define IDD_CHECKTOOL_FORM              131
#define IDD_DIALOG_CHECKTOOL            132
#define IDD_DIALOG_GRAYSTAT             133
#define IDD_DIALOG_TOPBAR               134
#define IDD_DIALOG_IMGBADPT             135
#define IDD_DIALOG_ABBRANCEBAR          136
#define IDD_DIALOG_STDCHKBAR            137
#define IDD_STDCHK_CAPTSPEED            138
#define IDD_DIALOG_CAPTIMAGES2SAVE      139
#define IDD_DIALOG_GRAYRAWOPT           140
#define IDD_DIALOG_SELCHANNEL           141
#define IDD_DIALOG_GRADUATIONX          142
#define IDD_DIALOG_GRADUATIONY          143
#define IDC_CURSOR1                     144
#define IDD_DIALOG_PHYDIST              145
#define IDD_DIALOG_SETSQUARE            146
#define IDD_DIALOG_IMAGESIZE            147
#define IDD_DIALOG1                     149
#define IDD_DIALOG_SETSERIALNO          149
#define IDC_STATIC_AREALEFTTOP          1000
#define IDC_STATIC_AREARIGHTBOTTOM      1001
#define IDC_STATIC_AREASIZE             1002
#define IDC_FORMVIEW_IDVALUE            1003
#define IDC_STATIC_FORMPLACE            1004
#define IDC_STATIC_FOCUSINFO_X          1005
#define IDC_STATIC_FOCUSINFO_Y          1006
#define IDC_STATIC_FOCUSINFO_GRAY       1007
#define IDC_CHECK_ONLYSHOWIMG           1008
#define IDC_STATIC_GRAYSTAT             1009
#define IDC_STATIC_AVERAGE              1010
#define IDC_STATIC_GRAYSTAT2            1011
#define IDC_STATIC_DIFF                 1012
#define IDC_STATIC_AVERAGE2             1013
#define IDC_STATIC_MEDIAN               1014
#define IDC_STATIC_DIFF2                1015
#define IDC_STATIC_PIXELCNT             1016
#define IDC_STATIC_MEDIAN2              1017
#define IDC_STATIC_RANGE                1018
#define IDC_STATIC_PIXELCNT2            1019
#define IDC_STATIC_CNTINRANGE           1020
#define IDC_STATIC_RANGE2               1021
#define IDC_STATIC_PERCENT              1022
#define IDC_STATIC_CNTINRANGE2          1023
#define IDC_STATIC_PERCENT2             1024
#define IDC_STATIC_AREAINFO             1025
#define IDC_STATIC_IMAGESIZE            1026
#define IDC_STATIC_BRIGHT               1027
#define IDC_CONTRAST_SCROLL             1028
#define IDC_BRIGHT_SCROLL               1029
#define IDC_STATIC_CONTRAST             1030
#define IDC_CHECK_STARTCAPTURE          1031
#define IDC_BTN_FROMFILE                1032
#define IDC_BTN_SAVE2FILE               1033
#define IDC_BTN_ZOOMOUT                 1034
#define IDC_BTN_ZOOMIN                  1035
#define IDC_STATIC_IMGSCALE             1036
#define IDC_CHECK_INSERTZOOM            1037
#define IDC_BTN_CAPTURESPEED            1038
#define IDC_EDIT_CAPTUREFRAME           1039
#define IDC_EDIT_CAPTURETIME            1040
#define IDC_EDIT_CAPTURESPEED           1041
#define IDC_CAPTURE_PROGRESS            1042
#define IDC_CHECK_SAVECAPTIMAGE         1043
#define IDC_EDIT_IMAGEFILEPATH          1044
#define IDC_BTN_IMAGEFILEPATH           1045
#define IDC_RADIO_IMGFMTBMP             1046
#define IDC_RADIO_IMGFMTRAW             1047
#define IDC_EDIT_IMAGEFILENAME          1048
#define IDC_STATIC_TIPINFO              1049
#define IDC_BTN_LODABACKIMAGE           1050
#define IDC_CHECK_SHOWBADPT             1051
#define IDC_STATIC_SHOWIMAGBADPT        1052
#define IDC_EDIT_IMGBADPTSTAT           1053
#define IDC_CHECK_IMGABBERACE           1054
#define IDC_EDIT_A1TOCENTER             1055
#define IDC_EDIT_A2TOCENTER             1056
#define IDC_EDIT_A3TOCENTER             1057
#define IDC_EDIT_A4TOCENTER             1058
#define IDC_EDIT_B1TOA1DIST             1059
#define IDC_EDIT_B1TOA2DIST             1060
#define IDC_EDIT_B2TOA2DIST             1061
#define IDC_EDIT_B2TOA3DIST             1062
#define IDC_EDIT_B3TOA3DIST             1063
#define IDC_EDIT_B3TOA4DIST             1064
#define IDC_EDIT_B4TOA4DIST             1065
#define IDC_EDIT_B4TOA1DIST             1066
#define IDC_EDIT_ABRRANCEVALUE          1067
#define IDC_BTN_CALCIMGABER             1068
#define IDC_STATIC_AVERAGE3             1069
#define IDC_STATIC_MEDIAN3              1070
#define IDC_STATIC_PIXELCNT3            1071
#define IDC_STATIC_DIFF3                1072
#define IDC_STATIC_STDCHKRESULT         1073
#define IDC_EDIT_STDCHKRESULT           1074
#define IDC_EDIT_STDCHK_ROLE            1076
#define IDC_STATIC_STDCHKTYPE           1077
#define IDC_EDIT_IMGWIDTH               1078
#define IDC_EDIT_IMGHEIGHT              1079
#define IDC_STATIC_DESC                 1080
#define IDC_STATIC_FILESIZE             1081
#define IDC_EDIT_IMAGEHEAD              1082
#define IDC_SPIN_CHANNEL                1083
#define IDC_EDIT_CHANNEL                1084
#define IDC_SPIN1                       1085
#define IDC_BTN_REVERSE                 1087
#define IDC_BUTTON1                     1088
#define IDC_BTN_PHYDISTANCE             1088
#define IDC_STATIC_DPI                  1089
#define IDC_EDIT_DISTANCE               1091
#define IDC_BTN_GAFISTEST               1091
#define IDC_CHECK_MOVESSQUARE           1092
#define IDC_EDIT_SQUAREWIDTH            1093
#define IDC_EDIT_SQUAREHEIGHT           1094
#define IDC_BUTTON_SETSQUARE            1095
#define IDC_CHECK_SHOWREDSQUARE         1096
#define IDC_CHECK_SHOWGREENSQUARE       1097
#define IDC_CHECK1                      1098
#define IDC_CHECK_SHOWBLUESQUARE        1098
#define IDC_EDIT_SN                     1099
#define IDC_BTN_SETSN                   1100
#define IDC_BUTTON3                     1101
#define IDC_BTN_GETSN                   1101
#define IDC_RADIO_SIZE_640_640          1102
#define IDC_RADIO_SIZE_440_440          1103
#define IDC_RADIO_SIZE_256_360          1104
#define IDC_RADIO_SIZE_CONFIG           1105
#define IDC_EDIT_SIZE_WIDTH             1106
#define IDC_EDIT2                       1107
#define IDC_EDIT_SIZE_LENGTH            1107
#define IDC_STATIC_WARN                 1108
#define IDC_EDIT_SERIALNO               1109
#define IDC_BLACKBALANCE_SCROLL         1110
#define IDC_STATIC_BLACKBALANCE         1111
#define ID_STDCHK_OPTICSDEVICE          32771
#define ID_STDCHK_CAPTURESIZE           32772
#define ID_STDCHK_VALIDIMAGESIZE        32773
#define ID_STDCHK_IMAGEPIXELCOUNT       32774
#define ID_STDCHK_CENTERDIFF            32775
#define ID_STDCHK_IMGRESOLUTION         32776
#define ID_STDCHK_IMGABERRANCE          32777
#define ID_STDCHK_IMGBACKGRAYAVERAGE    32778
#define ID_STDCHK_IMGBACKGRAYUNAVE      32779
#define ID_STDCHK_IMGCENTERGRAY         32780
#define ID_STDCHK_IMGGRAYVARIAN         32781
#define ID_STDCHK_IMGBADPOINT           32782
#define ID_STDCHK_ENVIRONMENT           32783
#define ID_STDCHK_IMGPARSE              32784
#define ID_STDCHK_CAPTSPEED             32785
#define ID_STDCHK_CAPTIMAGESTOSAVE      32786
#define ID_LOAD_LIVECAPTDLL             32787
#define ID_LOAD_MOSAICDLL               32788
#define ID_SCANNER_INITLIVECAPT         32791
#define ID_SCANNER_SELECTCHANNEL        32792
#define ID_SETPWH                       32793
#define ID_GETSETUPDLG                  32794
#define ID_ISISFIN                      32795
#define ID_ISSIMGQUA                    32796
#define ID_ISSFINQUA                    32797
#define ID_ISSIMGEN                     32800
#define ID_IMGQUA                       32801
#define ID_FINQUA                       32802
#define ID_IMGENH                       32803
#define ID_MENUITEM32805                32805
#define ID_MOSAIC_ROLL1FINGER           32806
#define ID_MOSAIC_ROLL2FINGER           32807
#define ID_MOSAIC_ROLL3FINGER           32808
#define ID_MOSAIC_PLAINFINGER           32809
#define ID_32810                        32810
#define ID_SCANNER_INITLIVECAPT2        32811
#define ID_SCANNER_INITLIVECAPT1        32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
