#ifndef FLAGS_H
#define FLAGS_H
/*
 * ENUM CMD & TYPE : Mon May  4 16:01:31 CST 2015
 */
enum CMD {
	CMD_LIGHT_ON = 1,
	CMD_LIGHT_OFF,
	CMD_LIGHT_BRIGHT,
	CMD_SCENE_LEAVE,
	CMD_SCENE_BACK,
	CMD_SCENE_DINNER,
	CMD_SCENE_MOVIE,
	CMD_SCENE_PARTY,
	CMD_SCENE_SLEEP,
	CMD_SCENE_NONE,
	CMD_SCENE_QUERY,
	CMD_CAMERA_PLAY,
	CMD_CAMERA_STOP,
	CMD_CURTAIN_OPEN,
	CMD_CURTAIN_CLOSE,
	CMD_CURTAIN_MIDDLE,	/* status */
	CMD_WINDOW_OPEN,
	CMD_WINDOW_CLOSE,
	CMD_WINDOW_MIDDLE,	/* status */
	CMD_GLASS_OPACITY,
	CMD_PROJECTOR_ON,
	CMD_PROJECTOR_OFF,
	CMD_ROBOT_FORWARD,
	CMD_ROBOT_BACKWARD,
	CMD_ROBOT_TURNLEFT,
	CMD_ROBOT_TURNRIGHT,
	CMD_ROBOT_STOP,		/* status */
	CMD_THEATRE_DVD,
	CMD_THEATRE_STB,
	CMD_THEATRE_CAMERA,
	CMD_GET_STATUS,
	CMD_SEND_FRAME,		/* back command */
	CMD_SENSOR_TEMP,
	CMD_SENSOR_HUMI,
	CMD_SENSOR_PM25,
	CMD_SENSOR_CO,
	CMD_SENSOR_DOOR,
	CMD_SENSOR_WIN,
	CMD_SENSOR_SMOKE,
	CMD_SENSOR_HUMAN,
	CMD_SENSOR_BRIGHT,
};

enum DEV_TYPE {
	DEV_TYPE_SCENE = 1,
	DEV_TYPE_LIGHT,
	DEV_TYPE_CAMERA,
	DEV_TYPE_CURTAIN,
	DEV_TYPE_WINDOW,
	DEV_TYPE_GLASS,
	DEV_TYPE_PROJECTOR,
	DEV_TYPE_ROBOT,
	DEV_TYPE_DVD,
	DEV_TYPE_STB,
	DEV_TYPE_THEATRE,
	DEV_TYPE_SENSOR_TEMP,
	DEV_TYPE_SENSOR_HUMI,
	DEV_TYPE_SENSOR_PM25,
	DEV_TYPE_SENSOR_CO,
	DEV_TYPE_SENSOR_DOOR,
	DEV_TYPE_SENSOR_WINDOW,
	DEV_TYPE_SENSOR_SMOKE,
	DEV_TYPE_SENSOR_HUMAN,
	DEV_TYPE_SENSOR_BRIGHT
};
#endif

